services:
  backend:
    image: pdubnyakov/morph-backend:latest
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
