apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8" />
      <title>Morphology demo</title>
    </head>
    <body>
      <h1>pyMorphy2 Demo</h1>
      <textarea id="input" rows="6" cols="60" placeholder="Enter some Russian text..."></textarea><br>
      <button onclick="analyze()">Analyze</button>
      <h2>Result:</h2>
      <pre id="output"></pre>
      <script>
        function analyze() {
          fetch('/api/analyze', {
              method: 'POST',
              headers: {'Content-Type': 'application/json'},
              body: JSON.stringify({text: document.getElementById('input').value})
          })
          .then(r => r.json())
          .then(data => document.getElementById('output').textContent = JSON.stringify(data, null, 2))
          .catch(e => document.getElementById('output').textContent = 'Error: ' + e);
        }
      </script>
    </body>
    </html>
  nginx.conf: |
    server {
      listen 80;
      server_name _;

      location /api/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }

      location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
      }
    }
