#cloud-config
debug:
    verbose: true
cloud_init_modules:
    - migrator
    - seed_random
    - write-files
    - growpart
    - resizefs
    - set_hostname
    - update_hostname
    - update_etc_hosts
    - users-groups
    - ssh
    - runcmd

users:
  - name: ubuntu
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    groups: [sudo]
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa <my ssh key>


package_update: true
package_upgrade: true
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - git
  - python3
  - python3-venv

write_files:
  - path: /etc/systemd/system/pymorphy2-backend.service
    content: |
      [Unit]
      Description=PyMorphy2 backend (Uvicorn + FastAPI)
      After=network.target

      [Service]
      Type=simple
      User=ubuntu
      WorkingDirectory=/opt/app/backend
      Environment="PATH=/opt/app/backend/venv/bin"
      ExecStart=/opt/app/backend/venv/bin/uvicorn app.main:app --host 0.0.0.0 --port 8000 --log-level debug
      Restart=on-failure

      [Install]
      WantedBy=multi-user.target

  - path: /etc/motd
    content: |
      ####################### PyMorphy2 is installed

runcmd:
  - mkdir -p /opt/app
  - chown ubuntu:ubuntu /opt/app
  - su - ubuntu -c "cd /opt/app && git clone https://github.com/pauldub04/cloud-pymorphy2 ."
  - su - ubuntu -c "cd /opt/app/backend && python3 -m venv venv"
  - su - ubuntu -c "cd /opt/app/backend && ./venv/bin/pip install --upgrade pip"
  - su - ubuntu -c "cd /opt/app/backend && ./venv/bin/pip install -r requirements.txt"
  - systemctl daemon-reload
  - systemctl enable pymorphy2-backend
  - systemctl restart pymorphy2-backend

final_message: |
  ####################### PyMorphy2 setup completed
  ####################### Logs: sudo journalctl -u pymorphy2-backend -f
