#cloud-config
debug:
    verbose: true
cloud_init_modules:
    - migrator
    - seed_random
    - write-files
    - growpart
    - resizefs
    - set_hostname
    - update_hostname
    - update_etc_hosts
    - users-groups
    - ssh
    - runcmd

users:
  - name: ubuntu
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    groups: [sudo, docker]
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQChs2uHa3YDyyL5WTOr6pt8+6soH0SxDlOvFPC9t/iEmsOGudt6MsTBMmJAZ2DOrTbU71Iy8FvSuilWBKD+iYIxjHGL/XaMslX1G4d3eAAqRMIo4PcBumGtv6aK1dhfXgsT2lkA8Yl+ARLkETOHE6haMckrZt8J5wkZgTC25Y9n76YpMU5b5D8z8Jze7nljbbyYLVuRSuE5NwJPUeOd8Wkmf0iubnWyJtKVevsHkF67prEh8g9LVZrd587R3Tuj33c5qPNpQ/m2KDD+AweHT1Vduc7FLUB92czEHKDKqnbd3REgsBQQzn+FiQYPy1XGOtB+uMjZ594S3xEpLPWz0qAfFb0Jt96k/kdvAI/7uzZb/4swtiR5o6gnt8FJu7V5DN872KqOmt+mo8fD0WYnmaEMH99syiYbqQmlCb83OdJzuHohVgSXKm6/OJOs9cOH1ixCjtyZCDihrr+ZmTqavh3kuV+as3TtQiha5RsaroxJ3hNhBT+GaI6VNUy4S12Kpxs= pdubnyakov@pdubnyakov-nix-2025-05-22
chpasswd:
  list: |
    ubuntu:hardpass1
  expire: false
ssh_pwauth: true
fqdn: "terraform-vm"

package_update: true
package_upgrade: true
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - git

write_files:
- path: /opt/app/docker-compose.yml
  encoding: b64
  content: ${docker_compose}
- path: /opt/app/nginx.conf
  encoding: b64
  content: ${nginx_conf}
- path: /opt/app/frontend/index.html
  encoding: b64
  content: ${index_html}
- path: /opt/app/frontend/script.js
  encoding: b64
  content: ${script_js}
- path: /etc/motd
  content: |
    ####################### Morph is installed
    ####################### http://<IP>:8000

runcmd:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - DEBIAN_FRONTEND=noninteractive sudo apt-get install -y docker-ce docker-ce-cli containerd.io
  - sudo systemctl enable docker
  - sudo systemctl start docker

  - curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose

  - sudo usermod -aG docker ubuntu

  - cd /opt/app
  - docker-compose up -d
